name: WorkerVless2sub-auto-sync

on:
  push:
    branches:
      -master
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *   # 每小时自动更新
  watch:                                                        # 监视操作
    types: [started]                                            # 点击 Star 之后
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.TOKEN }} # 令牌
          upstream_repository: cmliu/WorkerVless2sub  # 上游仓库地址
          target_repository: gxnas/WorkerVless2sub    # 要同步的仓库
          upstream_branch: main  # 默认是拉取上游仓库的main分支
          target_branch: main  # 默认推送到你的仓库main分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags

      - name: 清理Actions空间
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash

          # 获取7天以前的时间戳
          SEVEN_DAYS_AGO=$(date -d '-7 days' +%s)

          # 获取所有workflow runs
          WORKFLOW_RUNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100")

          # 逐个检查并删除超过7天的run
          for run_id in $(echo "$WORKFLOW_RUNS" | jq -r '.workflow_runs[] | select(.status == "completed") | .id'); do
            run_created_at=$(echo "$WORKFLOW_RUNS" | jq -r ".workflow_runs[] | select(.id == $run_id) | .created_at")
            run_created_at_ts=$(date -d "$run_created_at" +%s)

            if [[ $run_created_at_ts -lt $SEVEN_DAYS_AGO ]]; then
              echo "Deleting run $run_id created at $run_created_at"
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
            fi
          done
