name: WorkerVless2sub-auto-sync

on:
  push:
    branches:
      -master
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *   # 每小时自动更新
  watch:                                                        # 监视操作
    types: [started]                                            # 点击 Star 之后
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.TOKEN }} # 令牌
          upstream_repository: cmliu/WorkerVless2sub  # 上游仓库地址
          target_repository: gxnas/WorkerVless2sub    # 要同步的仓库
          upstream_branch: main  # 默认是拉取上游仓库的main分支
          target_branch: main  # 默认推送到你的仓库main分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags

      - name: 清理Actions空间
        continue-on-error: true
        if: env.REPO_TOKEN
        uses: small-5/delete-workflow-runs@main
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: 0
          retain_min: 0
